name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '**.zig'
    - '**.zon'
    - '**.c'
    - '**.h'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build Debug
        run: zig build

      - name: Build ReleaseSafe
        run: zig build -Doptimize=ReleaseSafe

      - name: Build 32-bit
        if: matrix.os == 'ubuntu-latest'
        run: zig build -Dtarget=arm-linux

      - name: Run Tests
        run: |
          zig build test -Doptimize=Debug
          zig build test -Doptimize=ReleaseFast
          zig build test -Doptimize=ReleaseSafe
          zig build test -Doptimize=ReleaseSmall

      - name: Run Tests MSVC
        if: matrix.os == 'windows-latest'
        run: |
          zig build test -Dtarget=native-windows-msvc -Doptimize=Debug
          zig build test -Dtarget=native-windows-msvc -Doptimize=ReleaseFast
          zig build test -Dtarget=native-windows-msvc -Doptimize=ReleaseSafe
          zig build test -Dtarget=native-windows-msvc -Doptimize=ReleaseSmall

      - name: Run Examples
        run: zig build all --build-file examples/build.zig
